language: cpp
os:
  - linux
compiler:
  - g++
script:
  - make -C HW2/Triangle_Problem make
  - make -C HW2/Triangle_Problem make test
  - make -C HW2/Triangle_Problem make gcov
  - make -C HW2/Triangle_Problem make clean
branches:
  only:
    - master
