language: cpp
compiler:
- g++
os:
- linux
script:
- make -C HW1/Triangle_Problem -C make
- make -C HW1/Triangle_Problem -C make test
- make -C HW1/Triangle_Problem -C make gcov
- make -C HW1/Triangle_Problem -C make clean
branches:
  only:
  - master